services:
  db:
    container_name: todo-db
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - todo:/var/lib/postgresql/data

  redis:
    container_name: todo-redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  app:
    container_name: todo-app
    build: .
    ports:
      - "7575:7575"
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  todo:

